### PR TITLE
Cycle through select

### PR DESCRIPTION
**Pull request by everlasterVR**
< button selects the final (visible) value in popupValues if current value is the first value
> button selects the first value in popupValues if current value is the final (visible) value

### CODE REVIEW

**Comment by acidbubbles** [comment]
@via5 do you have an opinion on that? My comment on Discord was:

>  I'm not sure about this; first, VaM arrows (e.g. in morphs) don't cycle, and I can easily see someone clicking on e.g. disable collision for each, you want to know when you're done, cycling means you need to read every time to know if you reached the last or not.

But a third opinion would be nice.

**Comment by via5** [comment]
I agree with you for cycling modified colliders, it's not a behaviour I'd be happy with. I fail to see a good use case for this.

**Comment by everlasterVR** [comment]
> I agree with you for cycling modified colliders, it's not a behaviour I'd be happy with. I fail to see a good use case for this.

The use case is navigating to the beginning or the end of the options list. It's not that this change would introduce that use case, but it was meant as a way to make that easier to do. It reduces the number of clicks, removes the need to have to move the mouse away from the prev/next button, and prevents from having to scroll the popup in case there's enough options in the list to require that. The popup element only has prev/next buttons, no buttons for start/end - so without letting the prev/next buttons cycle through the list, the only way to navigate to the beginning is to click the menu open, scroll it to the top/bottom and select the first/last item. I made this because I personally found it a bit awkward to have to do that.

I also thought the prev and next buttons being clickable when at the first/last item fits better with them actually doing some action. If they shouldn't cycle through then they should be disabled to indicate that that's intended :)

**Comment by via5** [comment]
> The use case is navigating to the beginning or the end of the options list.

That's what the feature does, it's not a use case. I'm trying to imagine a situation where wrapping around solves a problem, and I can't find one.

However, if you really need this, you could do something like a shift+click to go to the beginning/end. I'd be fine with that.

> If they shouldn't cycle through then they should be disabled to indicate that that's intended :)

I'd be okay with that too.

Note that this is AcidBubble's project, I'm just a tourist.

**Comment by acidbubbles** [comment]
Thanks, feedback appreciated. After talking with everlaster, I'll drop this one. It's an interesting idea but IMHO out of scope and without enough support for this project (maybe it could be a nice "global" improvement, not sure if it's feasible though)

**Pull request closed without merging**
